services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=book-lend
    ports:
      - "5432:5432"